---
version: "3"
services:
  filebrowser:
    # Upstream project website:
    # https://github.com/filebrowser/filebrowser
    image: docker.io/filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    command: >
      --database=/config/database.db --address=0.0.0.0 --port=8080
    volumes:
      - ./config:/config
      # Make directories on the host available within the container.
      # Adjust and add additional paths, as needed.
      # Remove ":ro" to enable write access.
      - /path/on/host:/srv:ro
    expose:
      - 8080
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      # Adjust subnet as needed
      - subnet: 172.16.1.0/27
